### ISSUE TITLE
Mismatch in datatype of DateCode 'components/component/transceiver/state/date-code' : implementation vs expectation

### ISSUE THREAD

**Issue by jyotigup-cisco** [openconfig/public#818] opened 2023-02-24 13:58 UTC
<p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">To bring to your notice, we observe that there is a mismatch of datatype of date-code in implementation and the expected value.</span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p>

 
--
DateCode     *string    `path:"state/date-code" module:"openconfig-platform-transceiver/openconfig-platform-transceiver"`
 

<p class="p1" style="font-size: 9pt; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-family: &quot;Helvetica Neue Light&quot;; color: rgb(15, 15, 15);"><span class="apple-converted-space"><b>   </b></span><b>|<span class="apple-converted-space">  </span>+--ro date-code<span class="apple-converted-space">                    </span><span style="background-color: yellow;">oc-yang:date-and-time</span></b><o:p></o:p></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;"> </span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">Hence unmarshalling fails with ondatra automation.</span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;"> </span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">Get(t) on dut(DUT) at &amp;{{Component_Transceiver true 0xc003b5d740 0x61c9a40 0x61c9ae0 0xc0030d8fc0 true}}: noncompliant data encountered while unmarshalling leaf: Noncompliance Errors by category:</span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">        Path Noncompliance Errors: None</span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">        Type Noncompliance Errors: None</span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">        Value Restriction Noncompliance Errors:</span><span style="font-size: 11pt; line-height: 1.2;"><o:p></o:p></span></p><p class="MsoNormal" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; white-space: normal; margin: 0cm; font-size: 10pt; font-family: Calibri, sans-serif; caret-color: rgb(33, 33, 33); color: rgb(33, 33, 33);"><span style="font-size: 11pt; line-height: 1.2;">                <span style="background-color: yellow;">/root/components/component/transceiver/state/date-code</span>: schema "date-code": "2022-10-17T00:00:00Z+00:00" does not match regular expression pattern "^([0-9]{4}\\-(0[1-9]|1[0-2])<a href="file:///-(0%5b1-9%5d|%5b12%5d%5b0-9%5d|3%5b01%5d)%5bTt%5d(0%5b0-9%5d|1%5b0-9%5d|2%5b0-3%5d):(0%5b0-9%5d|%5b1-5%5d%5b0-9%5d):(0%5b0-9%5d|%5b1-5%5d%5b0-9%5d|60)(/.%5b0-9%5d+)?(%5bZz%5d|(%5b+-%5d(0%5b0-9%5d|1%5b0-9%5d|2%5b0-3%5d):(0%5b0-9%5d|%5b1-5%5d%5b0-9%5d))))$" title="/-(0%5b1-9%5d|%5b12%5d%5b0-9%5d|3%5b01%5d)%5bTt%5d(0%5b0-9%5d|1%5b0-9%5d|2%5b0-3%5d):(0%5b0-9%5d|%5b1-5%5d%5b0-9%5d):(0%5b0-9%5d|%5b1-5%5d%5b0-9%5d|60)(/.%5b0-9%5d+)?(%5bZz%5d|(%5b+-%5d(0%5b0-9%5d|1%5b0-9%5d|2%5b0-3%5d):(0%5b0-9%5d|%5b1-5%5d%5b0-9%5d))))$" style="color: rgb(0, 120, 215); text-decoration: underline !important; -apple-color-filter: none;">\\-(0[1-9]|[12][0-9]|3[01])[Tt](0[0-9]|1[0-9]|2[0-3]):(0[0-9]|[1-5][0-9]):(0[0-9]|[1-5][0-9]|60)(\\.[0-9]+)?([Zz]|([+-](0[0-9]|1[0-9]|2[0-3]):(0[0-9]|[1-5][0-9]))))$</a>"</span></p>

**Comment by liulk** [comment] 2023-02-27 12:57
@greg-dennis @dang100 I think this is about ygnmi ygot-generated code, as @jyotigup-cisco discovered while working on https://github.com/openconfig/featureprofiles/pull/1188

**Comment by greg-dennis** [comment] 2023-02-27 15:47
@wenovus for any ygot implications

**Comment by DanG100** [comment] 2023-02-27 17:36
This is working as intended, the string "2022-10-17T00:00:00Z+00:00" does not match the regex and is not valid. Either  "Z" or "+00:00", but not both should be specified for a RFC3339 date and time string.

**Comment by liulk** [comment] 2023-02-27 18:14
Wow, thanks for looking! I missed that Z and UTC offset are mutually exclusive. Nice catch!

**Comment by dplore** [comment] 2023-03-01 21:46
Closing issue as intended behavior

**Closed by dplore** 2023-03-01 21:46 UTC
