### ISSUE TITLE
Prefix of iana-if-type.yang is changed during importing in openconfig-if-ethernet.yang

### ISSUE THREAD

**Issue by Nshet** [openconfig/public#219] opened 2019-04-12 08:47 UTC
I am seeing one issue in openconfig-if-ethernet.yang, please find below details
•	Container ethernet is augmented to openconfig-interfaces.yang when "oc-if:state/oc-if:type = 'ift:ethernetCsmacd'
•	Here ift is the prefix name of iana-if-type.yang. This yang is imported in openconfig-if-ethernet.yang like below
import iana-if-type { prefix ift; }
•	Actual prefix name of iana-if-type.yang is “ianaift”.
•	While publishing the results to confd, type of interface is  like “ianaift:ethernetCsmacd'.
•	Since prefix names plays key role while comparing “oc-if:state/oc-if:type = 'ift:ethernetCsmacd', so confd is not publishing the ethernet container results to Client.

Solution :

Modified openconfig-if-ethernet.yang like below

1)	import iana-if-type { prefix ift; } 
to 
              import iana-if-type { prefix ianaift; }

2)	when "oc-if:state/oc-if:type = 'ift:ethernetCsmacd'" {
to
                when "oc-if:state/oc-if:type = 'ianaift:ethernetCsmacd'"{

**Comment by exa-arrcus** [comment] 2019-04-12 15:16
The rule of thumb/best practice per YANG 1.0/1.1 although not always followed in practice is specified in section 7.1.4.  Any modules imported **_should_** follow this rule and be modified appropriately

```
7.1.4.  The prefix Statement
  ...
   When used inside the "module" statement, the "prefix" statement
   defines the prefix to be used when this module is imported.
```

However you'll note that YANG 1.1 modifies the wording to be a looser restriction

```
   When used inside the "module" statement, the "prefix" statement
   defines the prefix suggested to be used when this module is imported.
```

It may very well be possible that confd handles this differently for 1.0/1.1 however all OC models are currently 1.0

**Comment by aashaikh** [comment] 2019-04-16 08:04
I think the 1.1 language is what was intended for 1.0 as well -- i.e., I don't think it's required to use the prefix defined by the module -- it should be clear based on the `import` statement when the module is used.  I'm not sure I agree that confd is doing the right thing here.

We can open an issue to change openconfig-if-ethernet to use the prefix in iana-if-type, though we ultimately want to move to use openconfig-if-types.

**Comment by mbj4668** [comment] 2019-04-17 10:28
I agree that the model is correct.  (The bug in ConfD has been fixed in the latest version)

**Comment by aashaikh** [comment] 2019-04-21 01:53
We've updated the import prefixes for the iana-if-type and published a new version.  Note that we concluded here that this was a tooling issue (that's been fixed), not a bug in the models.

**Closed by aashaikh** 2019-04-21 01:53 UTC
