### ISSUE TITLE
openconfig-network-instances not validating below JSON

### ISSUE THREAD

**Issue by jambofun** [openconfig/public#597] opened 2022-03-05 17:42 UTC
I am trying to validate the below JSON data with the openconfig-network-instance.yang model. I am using Python yangson to do the validation, but I want to be sure the data is formatted corrrectly. The validation seems to complain of "openconfig-bgp:bgp" not being within the Schema but I know it is. Is is in the correct position? 

{
    "openconfig-network-instance:network-instances": {
        "network-instance": [
            {
                "name": "master",
                "config": {
                    "name": "master",
                    "type": "oc-ni-types:DEFAULT_INSTANCE",
                    "enabled": true
                },
                "protocols": {
                    "protocol": [
                        {
                            "identifier": "BGP",
                            "name": "openconfig-policy-types:BGP",
                            "config": {
                                "identifier": "BGP",
                                "name": "openconfig-policy-types:BGP",
                                "enabled": true
                            },
                            "openconfig-bgp:bgp": {
                                "global": {
                                    "as": 1234
                                }
                            }
                        }
                    ]
                }
            }
        ]
    }
}

**Comment by earies** [comment] 2022-03-05 18:49
Drop the prefix `openconfig-bgp: ` for your BGP stanza - from that anchor point onwards are groupings that are used from the BGP modules so the namespace/prefix become part of the parent `openconfig-network-instance`

In addition, `identifier` and `name` are flipped values of what they should be and `as` is a subset of the config/state containers at the `global` hierarchy

**Comment by jambofun** [comment] 2022-03-05 19:24
Thanks for the comments - interestingly, i now get the following error, im really not sure what this may indicate? 
Im aware its a Yangson exception, but it indicates that it was expecting the full model name?

`yangson.exceptions.SchemaError: {/} missing-data: expected 'openconfig-bgp:bgp'`

**Comment by earies** [comment] 2022-03-06 01:34
@jambofun - Are you using the `yangson` utility or using the library code directly - in either case can you share your command line arguments or relevant code?

**Comment by jambofun** [comment] 2022-03-06 09:41
Hi, I am using Python to do this, and have tried with the command-line utility and get the following:

`$ yangson openconfig-network-instance.json -v bgp-neighbour-instance.json
Illegal object member: /openconfig-network-instance:network-instances/network-instance=master/protocols/protocol=openconfig-policy-types:BGP,BGP/openconfig-bgp:bgp`

The following is the python code i am using for this, it is failing at the inst.validate() line: 

`filename = "openconfig-network-instance.json"
# print(type(filename))
dm = DataModel.from_file(filename)
print(dm)
print(dm.schema.description)
# print(dir(dm))

with open("bgp-neighbour-instance.json") as json_in:
    json_object = json.load(json_in)
    inst = dm.from_raw(json_object)
    inst.validate()`

**Comment by earies** [comment] 2022-03-06 16:04
It seems you will run into some issues w/ a few instance validators/linters and OC models as of today - `yangson` and `yanglint` for example (for different reasons/assumptions that could be argued as to the strictness/logic and lack of clarity in YANG 1.0)

With the following correct OC instance data and assuming a fully populated/correct set of yang-library instance data and assuming yangson validation of config r/w nodes only (By setting the `ctype`)

```
inst.validate(scope=ValidationScope.all, ctype=ContentType.config)
```

```
{
    "openconfig-network-instance:network-instances": {
        "network-instance": [
            {
                "name": "master",
                "config": {
                    "name": "master",
                    "type": "openconfig-network-instance-types:DEFAULT_INSTANCE",
                    "enabled": true
                },
                "protocols": {
                    "protocol": [
                        {
                            "identifier": "openconfig-policy-types:BGP",
                            "name": "BGP",
                            "config": {
                                "identifier": "openconfig-policy-types:BGP",
                                "name": "BGP",
                                "enabled": true
                            },
                            "bgp": {
                                "global": {
                                    "config": {
                                        "as": 65000
                                    }
                                }
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```
You should be faced with the following exception (on current 1.4.13 yangson libs)

```
yangson.exceptions.SchemaError: {/openconfig-network-instance:network-instances/network-instance[name="master"]/protocols/protocol[identifier="openconfig-policy-types:BGP"][name="BGP"]} config member-not-allowed: bgp
```
Which is due to handling of plain string equality checks - A similar issue was raised w/ yangson here: https://github.com/CZ-NIC/yangson/issues/41.  This issue has also been seen in `yanglint`

The suggestions in yangson indicate a change to the use of `derived-from` functions however this is a YANG 1.1 feature and OC models are YANG 1.0 currently.

For testing - you will notice that if you change the string equality match to the following you should succeed validation (Note for these matches, the prefix does not need to be qualified in the model by way of an import since it is merely a string match.  In addition, this may work for JSON encoding where the prefix is the module name but XML encoding could be any user-defined prefix as long as the xmlns is qualified which would again not work here)

```
--- a/release/models/network-instance/openconfig-network-instance.yang
+++ b/release/models/network-instance/openconfig-network-instance.yang
@@ -783,7 +783,7 @@ module openconfig-network-instance {
             }
 
             uses oc-bgp:bgp-top {
-              when "./config/identifier = 'oc-pol-types:BGP'" {
+              when "./config/identifier = 'openconfig-policy-types:BGP'" {
                 description
                   "Include BGP parameters only when the protocol
                   is of type BGP";
```

@robshakir @dplore - This issue is likely in need of further discussion as this is seen in multiple linters/validators when matching qualified identities with simple string comparisons

**Comment by jambofun** [comment] 2022-03-06 16:24
@earies Thanks for this - however funnily enough I did see a similar issue with yangson prior where i changed the when statement to the model name, instead of a prefix reference. During the earlier test, I had already changed this when statement to reflect the model name, but this gave the same output. 

Using exactly as you have above, I am getting the following issue: 

`$ yangson openconfig-network-instance.json -v bgp-neighbour-instance.json
Schema error: {/} missing-data: expected 'openconfig-bgp:bgp'`

and via Python:

`yangson.exceptions.SchemaError: {/} missing-data: expected 'openconfig-bgp:bgp'`


Is this an issue, or do you think something is off with a yang model somewhere?

**Comment by earies** [comment] 2022-03-06 17:01
@jambofun - That is likely coming by way of how the yang-library instance data is defined.  

Can you share the contents of `openconfig-network-instance.json` - The dependency chain of submodules and import vs. implement models is quite large for the network-instance model set.

**Comment by jambofun** [comment] 2022-03-06 17:05
@earies Sure, please find below. Happy to share any of the contents of any of these models if required with you. Many thanks again,

```
{
    "ietf-yang-library:modules-state": {
        "module-set-id": "ae4bf1ddf85a67ab94a9ab71593cd1c78b7f231d",
        "module": [
            {
                "name": "openconfig-bgp",
                "namespace": "http://openconfig.net/yang/bgp",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-bgp-common-multiprotocol",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-bgp-common-structure",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-bgp-peer-group",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-bgp-neighbor",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-bgp-global",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-bgp-common",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-policy-forwarding",
                "namespace": "http://openconfig.net/yang/policy-forwarding",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-pf-forwarding-policies",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-pf-path-groups",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-pf-interfaces",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-isis",
                "namespace": "http://openconfig.net/yang/openconfig-isis",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-isis-lsp",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-isis-routing",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-isis-types",
                "namespace": "http://openconfig.net/yang/isis-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-isis-lsdb-types",
                "namespace": "http://openconfig.net/yang/isis-lsdb-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-pim",
                "namespace": "http://openconfig.net/yang/pim",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-keychain",
                "namespace": "http://openconfig.net/yang/oc-keychain",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-igmp",
                "namespace": "http://openconfig.net/yang/igmp",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-igmp-types",
                "namespace": "http://openconfig.net/yang/igmp/types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-pim-types",
                "namespace": "http://openconfig.net/yang/pim/types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-keychain-types",
                "namespace": "http://openconfig.net/yang/oc-keychain-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-acl",
                "namespace": "http://openconfig.net/yang/acl",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-packet-match",
                "namespace": "http://openconfig.net/yang/packet-match-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-packet-match-types",
                "namespace": "http://openconfig.net/yang/header-fields",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-extensions",
                "namespace": "http://openconfig.net/yang/openconfig-ext",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-rib-bgp",
                "namespace": "http://openconfig.net/yang/rib/bgp",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-rib-bgp-attributes",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-rib-bgp-shared-attributes",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-rib-bgp-table-attributes",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-rib-bgp-tables",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-bgp-types",
                "namespace": "http://openconfig.net/yang/bgp-types",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-bgp-errors",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-types",
                "namespace": "http://openconfig.net/yang/openconfig-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "ietf-inet-types",
                "namespace": "urn:ietf:params:xml:ns:yang:ietf-inet-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-network-instance",
                "namespace": "http://openconfig.net/yang/network-instance",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-network-instance-l2",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-network-instance-types",
                "namespace": "http://openconfig.net/yang/network-instance-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-local-routing",
                "namespace": "http://openconfig.net/yang/local-routing",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-network-instance-l3",
                "namespace": "http://openconfig.net/yang/network-instance-l3",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-vlan",
                "namespace": "http://openconfig.net/yang/vlan",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-vlan-types",
                "namespace": "http://openconfig.net/yang/vlan-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-evpn-types",
                "namespace": "http://openconfig.net/yang/evpn-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-evpn",
                "namespace": "http://openconfig.net/yang/evpn",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-inet-types",
                "namespace": "http://openconfig.net/yang/types/inet",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "iana-if-type",
                "namespace": "urn:ietf:params:xml:ns:yang:iana-if-type",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "ietf-interfaces",
                "namespace": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-platform-types",
                "namespace": "http://openconfig.net/yang/platform-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-policy-types",
                "namespace": "http://openconfig.net/yang/policy-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "ietf-yang-types",
                "namespace": "urn:ietf:params:xml:ns:yang:ietf-yang-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-rib-bgp-types",
                "namespace": "http://openconfig.net/yang/rib/bgp-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-segment-routing-types",
                "namespace": "http://openconfig.net/yang/segment-routing/srte-policy",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-aft-types",
                "namespace": "http://openconfig.net/yang/fib-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-ospf-types",
                "namespace": "http://openconfig.net/yang/ospf-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-aft",
                "namespace": "http://openconfig.net/yang/aft",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-aft-ipv4",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-aft-ipv6",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-aft-mpls",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-aft-pf",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-aft-ethernet",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-aft-common",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-ospfv2",
                "namespace": "http://openconfig.net/yang/ospfv2",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-ospfv2-global",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-ospfv2-area",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-ospfv2-area-interface",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-ospfv2-common",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-ospfv2-lsdb",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-mpls-sr",
                "namespace": "http://openconfig.net/yang/mpls-sr",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-srte-policy",
                "namespace": "http://openconfig.net/yang/segment-routing-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-segment-routing",
                "namespace": "http://openconfig.net/yang/sr",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-routing-policy",
                "namespace": "http://openconfig.net/yang/routing-policy",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-bfd",
                "namespace": "http://openconfig.net/yang/bfd",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-yang-types",
                "namespace": "http://openconfig.net/yang/types/yang",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-rib-bgp-ext",
                "namespace": "http://openconfig.net/yang/rib/bgp-ext",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-8021x",
                "namespace": "http://openconfig.net/yang/interfaces/8021x",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-types",
                "namespace": "http://openconfig.net/yang/openconfig-if-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-ip-ext",
                "namespace": "http://openconfig.net/yang/interfaces/ip-ext",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-tunnel",
                "namespace": "http://openconfig.net/yang/interfaces/tunnel",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-bgp-policy",
                "namespace": "http://openconfig.net/yang/bgp-policy",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-ethernet",
                "namespace": "http://openconfig.net/yang/interfaces/ethernet",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-ip",
                "namespace": "http://openconfig.net/yang/interfaces/ip",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-sdn-ext",
                "namespace": "http://openconfig.net/interfaces/sdn-ext",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-aggregate",
                "namespace": "http://openconfig.net/yang/interfaces/aggregate",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-mpls",
                "namespace": "http://openconfig.net/yang/mpls",
                "revision": "",
                "conformance-type": "implement",
                "submodule": [
                    {
                        "name": "openconfig-mpls-te",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-mpls-igp",
                        "revision": ""
                    },
                    {
                        "name": "openconfig-mpls-static",
                        "revision": ""
                    }
                ]
            },
            {
                "name": "openconfig-mpls-rsvp",
                "namespace": "http://openconfig.net/yang/rsvp",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-mpls-ldp",
                "namespace": "http://openconfig.net/yang/ldp",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-mpls-types",
                "namespace": "http://openconfig.net/yang/mpls-types",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-ethernet-ext",
                "namespace": "http://openconfig.net/yang/interfaces/ethernet-ext",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-if-poe",
                "namespace": "http://openconfig.net/yang/poe",
                "revision": "",
                "conformance-type": "implement"
            },
            {
                "name": "openconfig-interfaces",
                "namespace": "http://openconfig.net/yang/interfaces",
                "revision": "",
                "conformance-type": "implement"
            }
        ]
    }
}
```

**Comment by earies** [comment] 2022-03-06 18:48
@jambofun - the yang-lib instance data looks fine and am able to validate given 2 temporary patches applied to the current OC model set from master - 1 patch is confirmed a bug being addressed in https://github.com/openconfig/public/pull/598 while the other is the patch I mentioned just to test the `when` condition above.

Is your OC instance-data as is defined in https://github.com/openconfig/public/issues/597#issuecomment-1059989670 ?

**Comment by jambofun** [comment] 2022-03-06 20:59
I will attempt tomorrow and update this comment accordingly. 

The only difference I see is that I commented out the openconfig-isis models as I was previously getting an InvalidLeafRefPath error. This could possibly be causing the issue? 

I will un-comment tomorrow and apply the leafref fix. 

Thanks again

**Comment by earies** [comment] 2022-03-07 20:46
@jambofun - are you still using your original instance data?  It appears so by that exception - note there are multiple issues w/ the original instance data so you'll want to use the correct per https://github.com/openconfig/public/issues/597#issuecomment-1059989670

**Comment by jambofun** [comment] 2022-03-07 20:58
@earies Yes - funnily enough I am actually using your exact instance data. Interesting why it seems to constantly complain of the same thing. 

Thanks

**Comment by earies** [comment] 2022-03-07 21:11
Your schema error indicates an issue at the top-level of `/` for BGP which leads me to believe this is an older BGP model where `/bgp` was still at the root.

It is very likely then a combination of your yang-library marking all models as `implement` and/or mandatory nodes are now the issue.  Since network-instance "imports" most models you can likely be more granular here and mark all BGP models as `import`.

Per the latest models published to master - `/bgp` no longer exists as it has been re-rooted under `/network-instances` from a few yrs back now.... (and recently completely removed)

**Comment by jambofun** [comment] 2022-03-08 08:56
@earies changing the conformance type for all BGP models in the JSON catalogue from "implement" to "import" seems to work. Really appreciate this

Out of interest in case I came across this again in the future, whats is the relationship between the BGP model and network-instance.yang? In other models, i can see an "augment" relationship which makes sense to me, but I am not sure with this one.

**Closed** 2022-03-10 09:24 UTC
